Syslog yes
SyslogSuccess yes
Canonicalization relaxed/relaxed
Mode s
OversignHeaders From
UserID opendkim
UMask 007
Socket inet:8891@127.0.0.1
PidFile /run/opendkim/opendkim.pid
Domain ulybnis24.ru
Selector site202610
KeyFile /etc/opendkim/keys/ulybnis24.ru/site202610.private
InternalHosts /etc/opendkim/trusted.hosts
ExternalIgnoreList /etc/opendkim/trusted.hosts
