# Generated by Django 5.2.14 on 2026-05-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='pricecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug'),
        ),
    ]
