# Generated by Django 5.2.14 on 2026-05-22 06:07

import clinic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_documentcategory_slug_alter_offer_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('block_type', models.CharField(choices=[('features', 'Преимущества'), ('content', 'Текстовый блок'), ('indications', 'Кому подойдет'), ('technologies', 'Технологии и услуги'), ('product_cards', 'Карточки систем/материалов'), ('steps', 'Этапы работы'), ('cta', 'Блок записи'), ('custom', 'Произвольный блок')], default='content', max_length=32, verbose_name='Тип блока')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/blocks/', validators=[clinic.models.validate_image], verbose_name='Изображение')),
                ('button_label', models.CharField(blank=True, max_length=120, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка кнопки')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='clinic.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Блок страницы услуги',
                'verbose_name_plural': 'Блоки страниц услуг',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicePageBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/block-items/', validators=[clinic.models.validate_image], verbose_name='Изображение')),
                ('price', models.CharField(blank=True, max_length=120, verbose_name='Цена')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='Метка')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные характеристики')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinic.servicepageblock', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Элемент блока услуги',
                'verbose_name_plural': 'Элементы блоков услуг',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
    ]
