# Generated by Django 5.2.14 on 2026-07-07 10:08

import clinic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_service_page_fields_and_sort_order_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='advantages/', validators=[clinic.models.validate_image], verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок героя')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Подзаголовок героя')),
                ('hero_button_text', models.CharField(blank=True, max_length=255, verbose_name='Текст кнопки героя')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/', validators=[clinic.models.validate_image], verbose_name='Изображение героя')),
                ('about_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок блока о клинике')),
                ('about_text', models.TextField(blank=True, verbose_name='Текст блока о клинике')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='pages/', validators=[clinic.models.validate_image], verbose_name='Изображение блока о клинике')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, verbose_name='Название сайта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', validators=[clinic.models.validate_image], verbose_name='Логотип')),
                ('copyright_text', models.CharField(blank=True, max_length=255, verbose_name='Копирайт в футере')),
                ('disclaimer', models.TextField(blank=True, verbose_name='Дисклеймер (противопоказания)')),
                ('cta_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок блока записи')),
                ('cta_subtitle', models.TextField(blank=True, verbose_name='Подзаголовок блока записи')),
                ('price_full_url', models.URLField(blank=True, verbose_name='Ссылка на полную версию прайса')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social-icons/', validators=[clinic.models.validate_image], verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Соцсеть',
                'verbose_name_plural': 'Соцсети',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('services', 'Услуги (список)'), ('prices', 'Цены'), ('doctors', 'Врачи (список)'), ('offers', 'Акции (список)'), ('reviews', 'Отзывы'), ('documents', 'Документы'), ('vacancies', 'Вакансии (список)'), ('policy', 'Политика конфиденциальности')], max_length=32, unique=True, verbose_name='Страница')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст (Markdown)')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
            ],
            options={
                'verbose_name': 'Статичная страница',
                'verbose_name_plural': 'Статичные страницы',
            },
        ),
        migrations.AddField(
            model_name='requisites',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='requisites/', validators=[clinic.models.validate_document], verbose_name='Файл с реквизитами (PDF)'),
        ),
        migrations.AddField(
            model_name='servicepageblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Текстовый блок'), ('cards', 'Карточки (карусель)')], default='text', max_length=16, verbose_name='Тип блока'),
        ),
        migrations.CreateModel(
            name='ServicePageBlockCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_text', models.CharField(blank=True, max_length=255, verbose_name='Цена (текст)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/block-cards/', validators=[clinic.models.validate_image], verbose_name='Изображение')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='clinic.servicepageblock', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Карточка блока услуги',
                'verbose_name_plural': 'Карточки блоков услуг',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
    ]
