# Generated by Django 5.2.14 on 2026-05-22 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_servicepageblock_servicepageblockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='clinic.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='review',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='clinic.specialist', verbose_name='Специалист'),
        ),
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='clinic.pricecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Группа прайса',
                'verbose_name_plural': 'Группы прайса',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='priceitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='clinic.pricegroup', verbose_name='Группа'),
        ),
    ]
