# Generated by Django 5.2.14 on 2026-07-07 11:30

import clinic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_advantage_homepage_sitesettings_sociallink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория специалистов',
                'verbose_name_plural': 'Категории специалистов',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст второй кнопки героя'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/icons/', validators=[clinic.models.validate_image], verbose_name='Иконка (сетка услуг)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service-categories/', validators=[clinic.models.validate_image], verbose_name='Фото карточки (главная)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (подпись на карточке)'),
        ),
        migrations.AlterField(
            model_name='servicepageblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Текстовый блок'), ('cards', 'Карточки (карусель)'), ('steps', 'Этапы (нумерованные карточки)')], default='text', max_length=16, verbose_name='Тип блока'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialists', to='clinic.specialistcategory', verbose_name='Категория'),
        ),
    ]
