# Generated by Django 5.2.14 on 2026-10-09 11:17

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_specialistcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='request_notification_emails',
            field=models.JSONField(blank=True, default=list, validators=[clinic.models.validate_email_list], verbose_name='Получатели заявок'),
        ),
    ]
